### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by vlovgr** [typelevel/vulcan#102]
Vulcan is already being used in production across several companies. We should therefore release a v1.0.0 to more explicitly communicate binary compatibility. Before committing to v1.0.0, it might be a good idea to squeeze in a few changes.

**Comment by bplommer** [comment]
How about we get https://github.com/fd4s/vulcan/pull/111 done before 1.0.0? I'm fairly sure I can finish it this weekend.

**Comment by vlovgr** [comment]
@bplommer sounds great! 👍

**Comment by vlovgr** [comment]
Done: https://github.com/fd4s/vulcan/releases/tag/v1.0.0
