### ISSUE TITLE
Dotty/ Scala 3 support

### ISSUE THREAD

**Issue by rmorais** [typelevel/vulcan#117]
if possible, we could add support for Dotty.
I will read into what is needed but given that Vulcan already supports scala 2.13, it should be simple.
Still need  to check dependencies

**Comment by bplommer** [comment]
If at some point we want to statically validate Avro schemas, I suspect we’ll have more luck if we do that in Dotty and then consider backporting it to Scala 2.

**Comment by bplommer** [comment]
I ran into https://github.com/lampepfl/dotty/issues/9492 while trying to port to scala 3.

**Comment by bplommer** [comment]
Resolved by #239
