### ISSUE TITLE
Schema resolution: conform more closely with Avro spec

### ISSUE THREAD

**Issue by bplommer** [typelevel/vulcan#132]
Writer schema validation is currently more strict than mandated by the Avro spec (https://avro.apache.org/docs/1.9.1/spec.html#Schema+Resolution), meaning schema evolutions that should be allowed are not.

- [x] ~Support promotion between different schema types, e.g. from `int` writer schema to `long` reader schema (#134)~
- [x] ~Match named schema based on `name` rather than `fullname` (#136)~
- [ ] Allow matching named schema based on aliases

We may not need to handle schema name matching ourselves at all, since it's already done by the underlying Avro library.

**Comment by vlovgr** [comment]
Moved alias support to #142.
