### ISSUE TITLE
Unsupported Avro type. Supported types are null, Boolean, Integer, Long, Float, Double, String, byte[] and IndexedRecord 

### ISSUE THREAD

**Issue by MarkRBM** [typelevel/vulcan#139]
I am trying to produce a key value pair of A, List[B] to kafka using avro, vulcan and a schema registry.

I am creating a serializer for list[B] like so

`avroSerializer[List[B]](Codec.List[B](bCodec)).using(SchemaRegistrySettings(conf)`

but at runtime I get 

Unsupported Avro type. Supported types are null, Boolean, Integer, Long, Float, Double, String, byte[] and IndexedRecord

and when I create a breakpoint for that exception it breaks in package `io.confluent.kafka.serializers.AvroSchemaUtils.getSchema`

and the method looks like this which does not seem to support array
```java
public static Schema getSchema(Object object) {
        if (object == null) {
            return (Schema)primitiveSchemas.get("Null");
        } else if (object instanceof Boolean) {
            return (Schema)primitiveSchemas.get("Boolean");
        } else if (object instanceof Integer) {
            return (Schema)primitiveSchemas.get("Integer");
        } else if (object instanceof Long) {
            return (Schema)primitiveSchemas.get("Long");
        } else if (object instanceof Float) {
            return (Schema)primitiveSchemas.get("Float");
        } else if (object instanceof Double) {
            return (Schema)primitiveSchemas.get("Double");
        } else if (object instanceof CharSequence) {
            return (Schema)primitiveSchemas.get("String");
        } else if (object instanceof byte[]) {
            return (Schema)primitiveSchemas.get("Bytes");
        } else if (object instanceof GenericContainer) {
            return ((GenericContainer)object).getSchema();
        } else {
            throw new IllegalArgumentException("Unsupported Avro type. Supported types are null, Boolean, Integer, Long, Float, Double, String, byte[] and IndexedRecord");
        }
    }
```

Am I doing something wrong? I wonder if I am having a dependency conflict and something is getting evicted but when I look at evicted in sbt everything is getting evicted for newer versions at least

**Comment by vlovgr** [comment]
@MarkRBM Looking at the Confluent serializer, which is what the fs2-kafka-vulcan module uses (vulcan does not depend on the Confluent serializer directly), it does indeed not support arrays as top-level type. In this case, you would have to wrap the list in a record, with e.g. a case class. So using e.g. `case class Record(list: List[A])` should work.

**Comment by MarkRBM** [comment]
thank you, would I have to make an equivelant change to my avro schema in the schema registry or should I be able to make all necessary changes just in my scala code do you think?

**Comment by vlovgr** [comment]
The schema in the schema registry will have to be updated as well, as the Confluent serialiser checks compatibility against the schema registry before serialising.
