### ISSUE TITLE
Derive unwrapped Codec for newtypes

### ISSUE THREAD

**Issue by mwz** [typelevel/vulcan#149]
It would be a small, but a nice feature to have vulcan automatically derive "unwrapped" codecs for value classes, similarly to what circe provides via the [eneric-extras](https://github.com/circe/circe-generic-extras/blob/master/generic-extras/src/main/scala/io/circe/generic/extras/semiauto.scala#L81) module, e.g.

```scala
final case class EventId(value: String)
```

Instead of 

```scala
Codec[String].imap(EventId.apply)(_.value)
```
we could just write the following to get the codec automatically derived:
```scala
Codec.deriveUnwrapped[EventId]
```

It's slightly shorter and easier to write if you use the generic module.

What do you think?

**Comment by vlovgr** [comment]
`Codec.derive` already has this behaviour for value classes (`extends AnyVal`). I’m not sure it’s worth having a separate construct for the non-value class case to shave off a few characters (plus the increase in compile time). 

Is there something I’m missing here?

**Comment by mwz** [comment]
Oh, I didn't realise it was already supported when using `AnyVal` - that's great! Thanks for clarifying this, it might be worth mentioning about it in the docs. I'll open a small PR when I get a chance.
