### ISSUE TITLE
Generic derivation for Scala 3

### ISSUE THREAD

**Issue by bplommer** [typelevel/vulcan#309]
Currently the `vulcan-generic` module is Scala 2 only, as it uses Magnolia.

**Comment by bplommer** [comment]
Currently the `vulcan-generic` module is Scala 2 only, as it uses Magnolia.

**Comment by custommonkey** [comment]
Does the softwaremill version of magnolia unlock things for scala 3 https://github.com/softwaremill/magnolia#availability

**Comment by bplommer** [comment]
Good shout @custommonkey, I'll look into that.

**Comment by mihaisoloi** [comment]
@bplommer I see that `vulcan-generic` is not published for Scala 3 but it's still mentioned in the docs as supported https://fd4s.github.io/vulcan/docs/overview#dependencies. Should we remove it from there? or is it a simple update to the latest magnolia version which it seems supports Scala 3

**Comment by bplommer** [comment]
Resolved in v1.8.0
