### ISSUE TITLE
Support for AvroName

### ISSUE THREAD

**Issue by gcollins-spark** [typelevel/vulcan#424]
#423 first pass, case class derive and derivefixed, some new tests passing

Before I go any further, is this a feature that would be useful? Is this draft PR going in the right direction? As I am not super-familiar with the Vulcan library and its various use cases, what else is left to implement?

**Comment by bplommer** [comment]
Thanks, it looks good to me - just running the tests now.

**Comment by bplommer** [comment]
Resolved in #423
