### ISSUE TITLE
Attribute namespace is optional in Enums

### ISSUE THREAD

**Issue by matheussbernardo** [typelevel/vulcan#472]
According to https://avro.apache.org/docs/1.11.1/specification/#enums the namespace attribute is optional in Enums. 
But Codec.enumeration does not allow for an optional namespace.

**Comment by vlovgr** [comment]
Hey @matheussbernardo, you should be able to use the empty `String` as namespace to achieve this.

**Comment by bplommer** [comment]
Yes, this is intentional as per https://github.com/fd4s/vulcan/issues/93. But note that Vulcan inherits from the Java implementation the restriction that you can *specify the null namespace* but you cannot *leave the namespace unspecified*.
