### ISSUE TITLE
Remove default "None" value for namespace of named types

### ISSUE THREAD

**Issue by bplommer** [typelevel/vulcan#93]
I think the default to `None` value should be removed for a couple of reasons:

- **It's confusing and potentially misleading**. The [Avro spec for names](https://avro.apache.org/docs/1.9.1/spec.html#names) makes an important but subtle distinction between *specifying the null namespace* (using the empty string) and *not specifying a namespace*: in the latter, and only the latter, case, the namespace from the closest enclosing scope is used. On the other hand, a Java `Schema` object will *always* specify a (possibly null) namespace. It's counterintuitive that, when the Avro API is invoked without specifying a namespace, the result is a type that specifies the null namespace.
- **Use of the null namespace should be discouraged**. Its semantics are confusing, and its implementation has bugs such as [this open issue from 2015](https://issues.apache.org/jira/browse/AVRO-1646) that took me two full days to identify as the cause of a decoding failure.

Better still (IMO) would be to make the `namespace` field non-optional, but allow use of the empty string, as per the Avro spec, to specify the null namespace. This retains the ability to specify the null namespace for those who know what they're doing, while no longer suggesting that it is a sensible default or that it is possible to leave the namespace unspecified.

I'm happy to open a PR for this - thoughts?

**Comment by vlovgr** [comment]
The only reason it hasn't changed to non-optional already is due to the change not being binary-compatible. Happy to accept a pull request for the next release breaking compatibility.
