### ISSUE TITLE
Relax validation of reader/writer schema type names during decoding

### ISSUE THREAD

**Issue by bplommer** [typelevel/vulcan#94]
The Vulcan decoders for named types impose stricter validation that the underlying Avro schema resolver, which allows a structural match based on fields if the names don't match between reader and writer schemas (see discussion [here](https://issues.apache.org/jira/browse/AVRO-1590?focusedCommentId=14146571&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14146571). 

That's a defensible design choice in itself, but in combination with Avro parsing bugs such as [this one](https://issues.apache.org/jira/browse/AVRO-1646) it results in decoding failures. Specifically, rendering a schema as json and then re-parsing it, as happens when a schema is published to a schema registry and then retrieved, can change the namespace of deeply nested types from `null` to the closest enclosing non-null namespace, as in the example given [here](https://github.com/apache/avro/pull/724). When a codec with this schema is used to publish and then read a message using fs2-kafka-vulcan, this results in an error because the record type's name in the schema retrieved from the schema registry doesn't match the name expected by the codec.

I'd suggest either removing the name validation entirely, or at least allowing a match based on `name` rather than `fullname` when the reader expects the null namespace. I'm happy to open a PR.

**Comment by vlovgr** [comment]
> allowing a match based on `name` rather than `fullname` when the reader expects the null namespace

This sounds reasonable to me. Feel free to open a pull request.

**Comment by bplommer** [comment]
I'm closing this as it's superseded by #111
